// Waqar Electronics - Comprehensive Products Database & Categories Engine

const CATEGORIES_DATA = {
  "air-conditioners": {
    name: "Air Conditioners",
    slug: "air-conditioners",
    icon: "ac_unit",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCSpLhuDFMtzwLUZHzABsZqRC40EoVMutIbNXXLHDnskftU5uILr5dCQadpJ8GEHR8IBOBm6RZDf1dCf-jlhrP1qlg4ULzVVh9CQylkadLfqR17ddTGzoRwa3_a9-BbiLr-DaqF7HRgB31eBUXvIs7kGFEuNzW7-6SjrjJuoGRJ_1xqmikl2ELQKY4N_dT-SKjddKfN4-FDaRwzvZ1JuKUs6GLVHGuzNIrrIx3aeeYjbWHam-yGSAgaZA",
    attrLabel: "Capacity",
    bannerSubtitle: "T3 Tropical Inverter & Non-Inverter Split ACs with Official Warranty and 0% Installment Plans.",
    attributes: ["1 Ton", "1.5 Ton", "2 Ton", "4 Ton"],
    brands: ["Gree", "Haier", "Dawlance", "Orient", "PEL", "TCL", "Kenwood"]
  },
  "refrigerators": {
    name: "Refrigerators",
    slug: "refrigerators",
    icon: "kitchen",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCIO0wF_mUwe-jMsGPzegZ4YXPWBZwVOQ_VkgfYfDSaabVTUL3JlQkPiu5UlKxVJ245k-CwF90fYJBe86cfs9h5mIytJyKEjp4s_36lTGSbeJndgf-_rRbZZGNLhGr4ilrM-AuaR4TwGXOC681HrezsC_qF5BpONzdeK_60VBk1Of1b7HSfJWmsHXEMzIZyhk2AppT7L-U_twq2pja_YCJ4Ta9vlBetsMjs_RGmqMjDKRmaYOtGUUOVsw",
    attrLabel: "Capacity (Cubic Feet)",
    bannerSubtitle: "Low Voltage Startup, Glass Door Inverter & Side-by-Side Refrigerators with NatureLock freshness.",
    attributes: ["11 cu ft", "14 cu ft", "16 cu ft", "18 cu ft", "20 cu ft"],
    brands: ["Dawlance", "Haier", "PEL", "Orient", "Samsung", "Waves", "Gree"]
  },
  "televisions": {
    name: "Smart TVs & Audio",
    slug: "televisions",
    icon: "tv",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuAqeFDCF7_CDJYqtgYHHniemMN_ZthYgQ0mFcmLVql8kS6JQHLpUqc7wyzP4Jl8A4GKlUvSgUfelNxbmxXQAjppJrgeROi2STK6GFZJDDkxuJegMVt2553HKv87uqHMitNSLMfJ3Bv2_FRRO5d1KYi-jrF4D-FG7v_58RgRc-tkxR7FaE2kz1KAb-6sdGqx6fLy8AJmBmQ2cgFHEBkxFaB3EfY6saWeCgkUeV70MGwdapIFKf5MHEyG4Q",
    attrLabel: "Screen Size",
    bannerSubtitle: "4K UHD, QLED, OLED & Google Smart TVs from leading global brands with cinema surround audio.",
    attributes: ["32 inch", "40 inch", "43 inch", "50 inch", "55 inch", "65 inch", "75 inch"],
    brands: ["Samsung", "TCL", "Sony", "Haier", "Ecostar", "Orient", "Changhong Ruba"]
  },
  "washing-machines": {
    name: "Washing Machines",
    slug: "washing-machines",
    icon: "local_laundry_service",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCm9tdMWpfp4TYdLEf86pxgej19uaGeQTcNxarbfwhwiz2onZ1SyFE5Vw4jMwtdObKVft1QpH1YujcrGeNAa-HQ3jml3sFOrpD_46o26NV53s9PuaqaEy6fs_clcG0bF2dlor1KCs3ae1MWJ3DKGhZ3f66oNFV6EleG0upqinZh8m6-wlmDj1vlGgPkbWuZYeNMpknZiB8p0-_7NDkIEoT88Pc5ZTQsetv0MYhQhKSgaQ13RqU3OkV9-w",
    attrLabel: "Capacity (Kg)",
    bannerSubtitle: "Fully Automatic Top-Load, Front-Load & Twin Tub Washers with Direct Drive Inverter motors.",
    attributes: ["8 Kg", "9.5 Kg", "10 Kg", "12 Kg", "15 Kg"],
    brands: ["Haier", "Dawlance", "Super Asia", "PEL", "Kenwood", "Samsung"]
  },
  "deep-freezers": {
    name: "Deep Freezers",
    slug: "deep-freezers",
    icon: "mode_heat",
    image: "images/deep-freezers.jpg",
    attrLabel: "Capacity (Cubic Feet)",
    bannerSubtitle: "Single & Double Door Convertible Inverter Freezers with 100-hour cooling retention.",
    attributes: ["10 cu ft", "12 cu ft", "14 cu ft", "16 cu ft", "18 cu ft"],
    brands: ["Waves", "Dawlance", "Haier", "PEL", "Orient"]
  },
  "microwave-ovens": {
    name: "Microwave Ovens",
    slug: "microwave-ovens",
    icon: "microwave",
    image: "images/microwave-ovens.jpg",
    attrLabel: "Volume",
    bannerSubtitle: "Solo, Grill & Convection Baking Microwave Ovens with built-in Pakistani recipe menus.",
    attributes: ["20L", "23L", "28L", "30L", "32L"],
    brands: ["Dawlance", "Haier", "PEL", "Homage", "Orient", "Panasonic"]
  },
  "air-coolers": {
    name: "Air Coolers",
    slug: "air-coolers",
    icon: "air",
    image: "images/air-coolers.jpg",
    attrLabel: "Tank Capacity",
    bannerSubtitle: "Honeycomb pad room air coolers with powerful ice-chamber cooling for instant relief.",
    attributes: ["25L", "35L", "45L", "55L", "70L"],
    brands: ["Boss", "Super Asia", "Canon", "Nasgas", "PEL", "National"]
  },
  "kitchen-appliances": {
    name: "Kitchen Hobs & Hoods",
    slug: "kitchen-appliances",
    icon: "skillet",
    image: "images/kitchen-hobs.jpg",
    attrLabel: "Type",
    bannerSubtitle: "Tempered glass gas hobs, auto-ignition stoves and high-suction chimney hoods.",
    attributes: ["2-Burner Hob", "3-Burner Hob", "Auto Chimney Hood", "Cooking Range 34\""],
    brands: ["Nasgas", "Canon", "Dawlance", "Haier", "Gaba National"]
  },
  "water-dispensers": {
    name: "Water Dispensers",
    slug: "water-dispensers",
    icon: "water_drop",
    image: "images/water-dispensers.jpg",
    attrLabel: "Design",
    bannerSubtitle: "3-Tap Hot, Cold & Normal dispensers with built-in refrigerator cabinet or bottom load.",
    attributes: ["3-Tap Refrigerator", "2-Tap Compact", "Bottom Load Inverter"],
    brands: ["Dawlance", "Haier", "Orient", "Homage", "PEL"]
  },
  "small-appliances": {
    name: "Small Home Appliances",
    slug: "small-appliances",
    icon: "blender",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCIO0wF_mUwe-jMsGPzegZ4YXPWBZwVOQ_VkgfYfDSaabVTUL3JlQkPiu5UlKxVJ245k-CwF90fYJBe86cfs9h5mIytJyKEjp4s_36lTGSbeJndgf-_rRbZZGNLhGr4ilrM-AuaR4TwGXOC681HrezsC_qF5BpONzdeK_60VBk1Of1b7HSfJWmsHXEMzIZyhk2AppT7L-U_twq2pja_YCJ4Ta9vlBetsMjs_RGmqMjDKRmaYOtGUUOVsw",
    attrLabel: "Category",
    bannerSubtitle: "Air fryers, food factories, heavy duty irons, vacuum cleaners and juicer blenders.",
    attributes: ["Air Fryer (5L-8L)", "Food Factory 10-in-1", "Heavy Dry Iron", "Drum Vacuum 21L"],
    brands: ["Philips", "Westpoint", "Anex", "Dawlance", "Panasonic", "Black & Decker"]
  }
};

const ALL_PRODUCTS = [
  // ================= AIR CONDITIONERS =================
  {
    id: 101,
    category: "air-conditioners",
    brand: "Gree",
    title: "Gree 1.5 Ton Fairy Series Heat & Cool Inverter AC (GS-18FITH)",
    model: "GS-18FITH1",
    attr_value: "1.5 Ton",
    price: 185000,
    was_price: 209000,
    emi: 15416,
    rating: 4.9,
    reviews: 142,
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCSpLhuDFMtzwLUZHzABsZqRC40EoVMutIbNXXLHDnskftU5uILr5dCQadpJ8GEHR8IBOBm6RZDf1dCf-jlhrP1qlg4ULzVVh9CQylkadLfqR17ddTGzoRwa3_a9-BbiLr-DaqF7HRgB31eBUXvIs7kGFEuNzW7-6SjrjJuoGRJ_1xqmikl2ELQKY4N_dT-SKjddKfN4-FDaRwzvZ1JuKUs6GLVHGuzNIrrIx3aeeYjbWHam-yGSAgaZA",
    warranty: "10 Years Compressor + 4 Years PCB Warranty",
    specs: { "Type": "T3 Inverter Heat & Cool", "SEER Rating": "3.8 Energy Efficient", "Refrigerant": "Eco-Friendly R410A", "Voltage": "Low Voltage 150V Support" },
    featured: true,
    lowest_30_days: true
  },
  {
    id: 102,
    category: "air-conditioners",
    brand: "Gree",
    title: "Gree 1.5 Ton Pular Series Inverter Heat & Cool AC (GS-18PITH11W)",
    model: "GS-18PITH11W",
    attr_value: "1.5 Ton",
    price: 176000,
    was_price: 190000,
    emi: 14660,
    rating: 5.0,
    reviews: 88,
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCRrpXp5vGlBLOxDOo_VeIAOYrcZ6jarRnLh-qcGNkMVw1Hf5t6q3wAPaemKBYhg5LEbfMiDlxZ988v64-PWwooAwiQH2ClVCcRRqbFOFfUBpdJUacjhaHsC01sszdFSY8MbZ56ibQXcsFkROhVvWHa959Fk0gDm64NHWbq14w5pBuBQQJjR1op99_-TYyIrW_T5LRt7HtiTY6Eg6KdyIpKEBjPfe2qgYrN9wgLWVvvMDI9658QNi32fA",
    warranty: "10 Years Compressor Warranty",
    specs: { "Type": "T3 Tropical Inverter", "Cooling at 68°C": "Supported", "Self-Cleaning": "Cold Plasma Air Purifier", "Display": "Hidden LED Display" },
    featured: true,
    lowest_30_days: true
  },
  {
    id: 103,
    category: "air-conditioners",
    brand: "Haier",
    title: "Haier 1.5 Ton Thunder Inverter AC Heat & Cool (HSU-18HFP)",
    model: "HSU-18HFPT3",
    attr_value: "1.5 Ton",
    price: 168000,
    was_price: 184000,
    emi: 14000,
    rating: 4.8,
    reviews: 95,
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCSpLhuDFMtzwLUZHzABsZqRC40EoVMutIbNXXLHDnskftU5uILr5dCQadpJ8GEHR8IBOBm6RZDf1dCf-jlhrP1qlg4ULzVVh9CQylkadLfqR17ddTGzoRwa3_a9-BbiLr-DaqF7HRgB31eBUXvIs7kGFEuNzW7-6SjrjJuoGRJ_1xqmikl2ELQKY4N_dT-SKjddKfN4-FDaRwzvZ1JuKUs6GLVHGuzNIrrIx3aeeYjbWHam-yGSAgaZA",
    warranty: "10 Years Compressor + 4 Years PCB Warranty",
    specs: { "Technology": "Thunder T3 Inverter", "WiFi Control": "Haier Smart App Support", "Electricity Saving": "Up to 65% Energy Saver", "Airflow": "4D Continuous Airflow" },
    featured: true,
    lowest_30_days: true
  },
  {
    id: 104,
    category: "air-conditioners",
    brand: "Dawlance",
    title: "Dawlance 1.5 Ton Chrome Pro Heat & Cool Inverter AC (30 Chrome)",
    model: "Mega-T3-30",
    attr_value: "1.5 Ton",
    price: 164000,
    was_price: 179000,
    emi: 13666,
    rating: 4.7,
    reviews: 64,
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCRrpXp5vGlBLOxDOo_VeIAOYrcZ6jarRnLh-qcGNkMVw1Hf5t6q3wAPaemKBYhg5LEbfMiDlxZ988v64-PWwooAwiQH2ClVCcRRqbFOFfUBpdJUacjhaHsC01sszdFSY8MbZ56ibQXcsFkROhVvWHa959Fk0gDm64NHWbq14w5pBuBQQJjR1op99_-TYyIrW_T5LRt7HtiTY6Eg6KdyIpKEBjPfe2qgYrN9wgLWVvvMDI9658QNi32fA",
    warranty: "12 Years Compressor + 4 Years PCB Warranty",
    specs: { "Compressor": "Gold Fin Condenser", "Dual Filtration": "Active Carbon Filter", "Voltage": "Operates down to 130V", "Mode": "Turbo Cool & Heat" },
    featured: false,
    lowest_30_days: false
  },
  {
    id: 105,
    category: "air-conditioners",
    brand: "Gree",
    title: "Gree 1.0 Ton Fairy Series T3 Inverter AC (GS-12FITH)",
    model: "GS-12FITH",
    attr_value: "1 Ton",
    price: 138000,
    was_price: 152000,
    emi: 11500,
    rating: 4.8,
    reviews: 52,
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCSpLhuDFMtzwLUZHzABsZqRC40EoVMutIbNXXLHDnskftU5uILr5dCQadpJ8GEHR8IBOBm6RZDf1dCf-jlhrP1qlg4ULzVVh9CQylkadLfqR17ddTGzoRwa3_a9-BbiLr-DaqF7HRgB31eBUXvIs7kGFEuNzW7-6SjrjJuoGRJ_1xqmikl2ELQKY4N_dT-SKjddKfN4-FDaRwzvZ1JuKUs6GLVHGuzNIrrIx3aeeYjbWHam-yGSAgaZA",
    warranty: "10 Years Compressor Warranty",
    specs: { "Capacity": "12000 BTU", "Coverage": "Ideal for 10x12 ft Room", "Refrigerant": "R410A", "Sound Level": "Ultra Quiet 24dB" },
    featured: false,
    lowest_30_days: true
  },
  {
    id: 106,
    category: "air-conditioners",
    brand: "Dawlance",
    title: "Dawlance 2.0 Ton Powercon Inverter AC Heat & Cool",
    model: "D-Powercon-24",
    attr_value: "2 Ton",
    price: 245000,
    was_price: 270000,
    emi: 20416,
    rating: 4.9,
    reviews: 38,
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCRrpXp5vGlBLOxDOo_VeIAOYrcZ6jarRnLh-qcGNkMVw1Hf5t6q3wAPaemKBYhg5LEbfMiDlxZ988v64-PWwooAwiQH2ClVCcRRqbFOFfUBpdJUacjhaHsC01sszdFSY8MbZ56ibQXcsFkROhVvWHa959Fk0gDm64NHWbq14w5pBuBQQJjR1op99_-TYyIrW_T5LRt7HtiTY6Eg6KdyIpKEBjPfe2qgYrN9wgLWVvvMDI9658QNi32fA",
    warranty: "12 Years Compressor Warranty",
    specs: { "Capacity": "24000 BTU Heavy Duty", "Coverage": "Hall & Large Living Rooms", "Fin Protection": "Rust-Free Hydrophilic Gold Fin" },
    featured: false,
    lowest_30_days: false
  },
  {
    id: 107,
    category: "air-conditioners",
    brand: "TCL",
    title: "TCL 1.5 Ton T-Pro Fresh Air Smart Inverter AC (TAC-18TPRO)",
    model: "TAC-18TPRO",
    attr_value: "1.5 Ton",
    price: 159000,
    was_price: 175000,
    emi: 13250,
    rating: 4.6,
    reviews: 41,
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCSpLhuDFMtzwLUZHzABsZqRC40EoVMutIbNXXLHDnskftU5uILr5dCQadpJ8GEHR8IBOBm6RZDf1dCf-jlhrP1qlg4ULzVVh9CQylkadLfqR17ddTGzoRwa3_a9-BbiLr-DaqF7HRgB31eBUXvIs7kGFEuNzW7-6SjrjJuoGRJ_1xqmikl2ELQKY4N_dT-SKjddKfN4-FDaRwzvZ1JuKUs6GLVHGuzNIrrIx3aeeYjbWHam-yGSAgaZA",
    warranty: "10 Years Compressor + 4 Years PCB Warranty",
    specs: { "Smart Control": "IoT WiFi App & Google Voice", "Deep Clean": "56°C High Temp Self-Sterilization", "Energy Saving": "Up to 60%" },
    featured: false,
    lowest_30_days: true
  },
  {
    id: 108,
    category: "air-conditioners",
    brand: "PEL",
    title: "PEL 1.5 Ton Jumbo DC Inverter Heat & Cool AC (Pinacle Series)",
    model: "PEL-Pinacle-18K",
    attr_value: "1.5 Ton",
    price: 154000,
    was_price: 168000,
    emi: 12833,
    rating: 4.5,
    reviews: 33,
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCRrpXp5vGlBLOxDOo_VeIAOYrcZ6jarRnLh-qcGNkMVw1Hf5t6q3wAPaemKBYhg5LEbfMiDlxZ988v64-PWwooAwiQH2ClVCcRRqbFOFfUBpdJUacjhaHsC01sszdFSY8MbZ56ibQXcsFkROhVvWHa959Fk0gDm64NHWbq14w5pBuBQQJjR1op99_-TYyIrW_T5LRt7HtiTY6Eg6KdyIpKEBjPfe2qgYrN9wgLWVvvMDI9658QNi32fA",
    warranty: "10 Years Compressor Warranty",
    specs: { "Compressor": "Aowei T3 Compressor", "Cooling": "Full 18000 BTU cooling", "Air Throw": "35+ Feet Powerful Throw" },
    featured: false,
    lowest_30_days: false
  },

  // ================= REFRIGERATORS =================
  {
    id: 201,
    category: "refrigerators",
    brand: "Dawlance",
    title: "Dawlance 91999 Avante Inverter Refrigerator (18 cu ft)",
    model: "91999-Avante-Inv",
    attr_value: "18 cu ft",
    price: 142500,
    was_price: 161000,
    emi: 11875,
    rating: 4.9,
    reviews: 42,
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCIO0wF_mUwe-jMsGPzegZ4YXPWBZwVOQ_VkgfYfDSaabVTUL3JlQkPiu5UlKxVJ245k-CwF90fYJBe86cfs9h5mIytJyKEjp4s_36lTGSbeJndgf-_rRbZZGNLhGr4ilrM-AuaR4TwGXOC681HrezsC_qF5BpONzdeK_60VBk1Of1b7HSfJWmsHXEMzIZyhk2AppT7L-U_twq2pja_YCJ4Ta9vlBetsMjs_RGmqMjDKRmaYOtGUUOVsw",
    warranty: "12 Years Compressor Warranty",
    specs: { "Energy Rating": "A++ Inverter (55% Saver)", "Freshness": "Nature Lock Vegetable Box", "Voltage": "Runs on 135V Without Stabilizer", "Lighting": "Hybrid Edge LED" },
    featured: true,
    lowest_30_days: true
  },
  {
    id: 202,
    category: "refrigerators",
    brand: "Haier",
    title: "Haier 16 cu ft Digital Inverter Glass Door Refrigerator (HRF-398IDG)",
    model: "HRF-398IDG",
    attr_value: "16 cu ft",
    price: 136000,
    was_price: 149000,
    emi: 11333,
    rating: 4.8,
    reviews: 58,
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCIO0wF_mUwe-jMsGPzegZ4YXPWBZwVOQ_VkgfYfDSaabVTUL3JlQkPiu5UlKxVJ245k-CwF90fYJBe86cfs9h5mIytJyKEjp4s_36lTGSbeJndgf-_rRbZZGNLhGr4ilrM-AuaR4TwGXOC681HrezsC_qF5BpONzdeK_60VBk1Of1b7HSfJWmsHXEMzIZyhk2AppT7L-U_twq2pja_YCJ4Ta9vlBetsMjs_RGmqMjDKRmaYOtGUUOVsw",
    warranty: "10 Years Compressor Warranty",
    specs: { "Compressor": "2nd Gen Inverter Compressor", "Cooling System": "Twin Inverter Tech", "Freezer Ratio": "Mega Freezer with 4 Drawers" },
    featured: false,
    lowest_30_days: true
  },
  {
    id: 203,
    category: "refrigerators",
    brand: "PEL",
    title: "PEL 14 cu ft Desire Glass Door Inverter Refrigerator (PRGD-21950)",
    model: "PRGD-21950",
    attr_value: "14 cu ft",
    price: 108000,
    was_price: 119000,
    emi: 9000,
    rating: 4.6,
    reviews: 29,
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCIO0wF_mUwe-jMsGPzegZ4YXPWBZwVOQ_VkgfYfDSaabVTUL3JlQkPiu5UlKxVJ245k-CwF90fYJBe86cfs9h5mIytJyKEjp4s_36lTGSbeJndgf-_rRbZZGNLhGr4ilrM-AuaR4TwGXOC681HrezsC_qF5BpONzdeK_60VBk1Of1b7HSfJWmsHXEMzIZyhk2AppT7L-U_twq2pja_YCJ4Ta9vlBetsMjs_RGmqMjDKRmaYOtGUUOVsw",
    warranty: "10 Years Compressor Warranty",
    specs: { "Glass": "Anti-Scratch Toughened Glass", "Crisper": "Ag+ Antibacterial Gasket", "Deodorizer": "Active Carbon Filter" },
    featured: false,
    lowest_30_days: false
  },
  {
    id: 204,
    category: "refrigerators",
    brand: "Samsung",
    title: "Samsung 20 cu ft Side-by-Side SpaceMax Smart Inverter Refrigerator",
    model: "RS52B3000M9",
    attr_value: "20 cu ft",
    price: 365000,
    was_price: 395000,
    emi: 30416,
    rating: 5.0,
    reviews: 19,
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCIO0wF_mUwe-jMsGPzegZ4YXPWBZwVOQ_VkgfYfDSaabVTUL3JlQkPiu5UlKxVJ245k-CwF90fYJBe86cfs9h5mIytJyKEjp4s_36lTGSbeJndgf-_rRbZZGNLhGr4ilrM-AuaR4TwGXOC681HrezsC_qF5BpONzdeK_60VBk1Of1b7HSfJWmsHXEMzIZyhk2AppT7L-U_twq2pja_YCJ4Ta9vlBetsMjs_RGmqMjDKRmaYOtGUUOVsw",
    warranty: "20 Years Digital Inverter Warranty",
    specs: { "Technology": "SpaceMax High Urethane Insulation", "Cooling": "All-Around Cooling System", "Finish": "Gentle Silver Matt Stainless Steel" },
    featured: true,
    lowest_30_days: false
  },
  {
    id: 205,
    category: "refrigerators",
    brand: "Dawlance",
    title: "Dawlance 9170 WB Avante Series Refrigerator (14 cu ft)",
    model: "9170-WB-Avante",
    attr_value: "14 cu ft",
    price: 112000,
    was_price: 124000,
    emi: 9333,
    rating: 4.7,
    reviews: 67,
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCIO0wF_mUwe-jMsGPzegZ4YXPWBZwVOQ_VkgfYfDSaabVTUL3JlQkPiu5UlKxVJ245k-CwF90fYJBe86cfs9h5mIytJyKEjp4s_36lTGSbeJndgf-_rRbZZGNLhGr4ilrM-AuaR4TwGXOC681HrezsC_qF5BpONzdeK_60VBk1Of1b7HSfJWmsHXEMzIZyhk2AppT7L-U_twq2pja_YCJ4Ta9vlBetsMjs_RGmqMjDKRmaYOtGUUOVsw",
    warranty: "12 Years Compressor Warranty",
    specs: { "Lock": "Health Zone Antibacterial Protect", "Shelves": "Spill-Proof Tempered Glass", "Gas": "100% CFC Free R600a" },
    featured: false,
    lowest_30_days: false
  },

  // ================= SMART TVS & AUDIO =================
  {
    id: 301,
    category: "televisions",
    brand: "Samsung",
    title: "Samsung 65\" Crystal 4K UHD Smart TV (CU7000 Series)",
    model: "UA65CU7000",
    attr_value: "65 inch",
    price: 249900,
    was_price: 275000,
    emi: 20825,
    rating: 4.8,
    reviews: 31,
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuAqeFDCF7_CDJYqtgYHHniemMN_ZthYgQ0mFcmLVql8kS6JQHLpUqc7wyzP4Jl8A4GKlUvSgUfelNxbmxXQAjppJrgeROi2STK6GFZJDDkxuJegMVt2553HKv87uqHMitNSLMfJ3Bv2_FRRO5d1KYi-jrF4D-FG7v_58RgRc-tkxR7FaE2kz1KAb-6sdGqx6fLy8AJmBmQ2cgFHEBkxFaB3EfY6saWeCgkUeV70MGwdapIFKf5MHEyG4Q",
    warranty: "1 Year Official Samsung Pakistan Panel Warranty",
    specs: { "Resolution": "3840 x 2160 (4K UHD)", "HDR": "HDR 10+ PurColor Engine", "OS": "Tizen Smart TV OS", "Audio": "OTS Lite with Q-Symphony" },
    featured: true,
    lowest_30_days: true
  },
  {
    id: 302,
    category: "televisions",
    brand: "TCL",
    title: "TCL 55\" C645 QLED 4K Google Smart TV 120Hz DLG (55C645)",
    model: "55C645-QLED",
    attr_value: "55 inch",
    price: 169000,
    was_price: 188000,
    emi: 14083,
    rating: 4.9,
    reviews: 54,
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuAqeFDCF7_CDJYqtgYHHniemMN_ZthYgQ0mFcmLVql8kS6JQHLpUqc7wyzP4Jl8A4GKlUvSgUfelNxbmxXQAjppJrgeROi2STK6GFZJDDkxuJegMVt2553HKv87uqHMitNSLMfJ3Bv2_FRRO5d1KYi-jrF4D-FG7v_58RgRc-tkxR7FaE2kz1KAb-6sdGqx6fLy8AJmBmQ2cgFHEBkxFaB3EfY6saWeCgkUeV70MGwdapIFKf5MHEyG4Q",
    warranty: "2 Years Official TCL Pakistan Warranty",
    specs: { "Display": "Quantum Dot 1 Billion+ Colors", "Audio": "Dolby Atmos + DTS-HD", "Gaming": "Game Master 2.0 with AMD FreeSync", "OS": "Google TV with Hands-free Voice" },
    featured: false,
    lowest_30_days: true
  },
  {
    id: 303,
    category: "televisions",
    brand: "Sony",
    title: "Sony BRAVIA 55\" 4K HDR Google Smart TV (KD-55X75K)",
    model: "KD-55X75K",
    attr_value: "55 inch",
    price: 215000,
    was_price: 235000,
    emi: 17916,
    rating: 4.9,
    reviews: 28,
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuAqeFDCF7_CDJYqtgYHHniemMN_ZthYgQ0mFcmLVql8kS6JQHLpUqc7wyzP4Jl8A4GKlUvSgUfelNxbmxXQAjppJrgeROi2STK6GFZJDDkxuJegMVt2553HKv87uqHMitNSLMfJ3Bv2_FRRO5d1KYi-jrF4D-FG7v_58RgRc-tkxR7FaE2kz1KAb-6sdGqx6fLy8AJmBmQ2cgFHEBkxFaB3EfY6saWeCgkUeV70MGwdapIFKf5MHEyG4Q",
    warranty: "1 Year Official Sony Warranty",
    specs: { "Processor": "4K Processor X1", "Clarity": "4K X-Reality PRO Upscaling", "Protection": "X-Protection PRO (Dust & Surge Proof)" },
    featured: false,
    lowest_30_days: false
  },
  {
    id: 304,
    category: "televisions",
    brand: "Haier",
    title: "Haier 43\" Smart Bezel-less FHD Google TV (H43K800F)",
    model: "H43K800F",
    attr_value: "43 inch",
    price: 76500,
    was_price: 84000,
    emi: 6375,
    rating: 4.7,
    reviews: 73,
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuAqeFDCF7_CDJYqtgYHHniemMN_ZthYgQ0mFcmLVql8kS6JQHLpUqc7wyzP4Jl8A4GKlUvSgUfelNxbmxXQAjppJrgeROi2STK6GFZJDDkxuJegMVt2553HKv87uqHMitNSLMfJ3Bv2_FRRO5d1KYi-jrF4D-FG7v_58RgRc-tkxR7FaE2kz1KAb-6sdGqx6fLy8AJmBmQ2cgFHEBkxFaB3EfY6saWeCgkUeV70MGwdapIFKf5MHEyG4Q",
    warranty: "2 Years Panel Warranty",
    specs: { "Bezel": "Ultra-Slim Metal Bezel-less", "Built-in": "Chromecast & Google Assistant", "Sound": "Dolby Digital Audio Decoding" },
    featured: false,
    lowest_30_days: true
  },
  {
    id: 305,
    category: "televisions",
    brand: "Ecostar",
    title: "Ecostar 32\" Frameless HD Smart LED TV (CX-32U571)",
    model: "CX-32U571",
    attr_value: "32 inch",
    price: 36000,
    was_price: 40000,
    emi: 3000,
    rating: 4.6,
    reviews: 84,
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuAqeFDCF7_CDJYqtgYHHniemMN_ZthYgQ0mFcmLVql8kS6JQHLpUqc7wyzP4Jl8A4GKlUvSgUfelNxbmxXQAjppJrgeROi2STK6GFZJDDkxuJegMVt2553HKv87uqHMitNSLMfJ3Bv2_FRRO5d1KYi-jrF4D-FG7v_58RgRc-tkxR7FaE2kz1KAb-6sdGqx6fLy8AJmBmQ2cgFHEBkxFaB3EfY6saWeCgkUeV70MGwdapIFKf5MHEyG4Q",
    warranty: "2 Years Official Warranty",
    specs: { "Screen": "Grade A+ IPS Panel", "Connectivity": "2 HDMI, 2 USB, Optical Out", "Smart": "Android 11 with YouTube & Netflix" },
    featured: false,
    lowest_30_days: false
  },

  // ================= WASHING MACHINES =================
  {
    id: 401,
    category: "washing-machines",
    brand: "Haier",
    title: "Haier 12 Kg Fully Automatic Top Load Washing Machine (HWM-120-1789)",
    model: "HWM-120-1789",
    attr_value: "12 Kg",
    price: 104000,
    was_price: 118000,
    emi: 8666,
    rating: 4.9,
    reviews: 56,
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCm9tdMWpfp4TYdLEf86pxgej19uaGeQTcNxarbfwhwiz2onZ1SyFE5Vw4jMwtdObKVft1QpH1YujcrGeNAa-HQ3jml3sFOrpD_46o26NV53s9PuaqaEy6fs_clcG0bF2dlor1KCs3ae1MWJ3DKGhZ3f66oNFV6EleG0upqinZh8m6-wlmDj1vlGgPkbWuZYeNMpknZiB8p0-_7NDkIEoT88Pc5ZTQsetv0MYhQhKSgaQ13RqU3OkV9-w",
    warranty: "10 Years Motor + 3 Years Panel Warranty",
    specs: { "Pulsator": "Storm Wash Pulsator", "Drum": "Pillow Stainless Steel Drum", "Lid": "Soft Fall Hydraulic Glass Lid", "Pressure": "Near Zero Water Pressure Work" },
    featured: true,
    lowest_30_days: true
  },
  {
    id: 402,
    category: "washing-machines",
    brand: "Dawlance",
    title: "Dawlance 10 Kg Fully Automatic Top Load Washer (DWT 270 C LVS)",
    model: "DWT-270-C-LVS",
    attr_value: "10 Kg",
    price: 92000,
    was_price: 104000,
    emi: 7666,
    rating: 4.8,
    reviews: 44,
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCm9tdMWpfp4TYdLEf86pxgej19uaGeQTcNxarbfwhwiz2onZ1SyFE5Vw4jMwtdObKVft1QpH1YujcrGeNAa-HQ3jml3sFOrpD_46o26NV53s9PuaqaEy6fs_clcG0bF2dlor1KCs3ae1MWJ3DKGhZ3f66oNFV6EleG0upqinZh8m6-wlmDj1vlGgPkbWuZYeNMpknZiB8p0-_7NDkIEoT88Pc5ZTQsetv0MYhQhKSgaQ13RqU3OkV9-w",
    warranty: "10 Years Motor Warranty",
    specs: { "Feature": "Low Voltage Support (LVS 150V)", "Wash": "Pro Fabric Care Wave Drum", "Noise": "Silent Drive Operation" },
    featured: false,
    lowest_30_days: true
  },
  {
    id: 403,
    category: "washing-machines",
    brand: "Super Asia",
    title: "Super Asia 10 Kg Twin Tub Heavy Duty Washer & Spinner (SA-290)",
    model: "SA-290-Shower-Spin",
    attr_value: "10 Kg",
    price: 37500,
    was_price: 42000,
    emi: 3125,
    rating: 4.7,
    reviews: 91,
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCm9tdMWpfp4TYdLEf86pxgej19uaGeQTcNxarbfwhwiz2onZ1SyFE5Vw4jMwtdObKVft1QpH1YujcrGeNAa-HQ3jml3sFOrpD_46o26NV53s9PuaqaEy6fs_clcG0bF2dlor1KCs3ae1MWJ3DKGhZ3f66oNFV6EleG0upqinZh8m6-wlmDj1vlGgPkbWuZYeNMpknZiB8p0-_7NDkIEoT88Pc5ZTQsetv0MYhQhKSgaQ13RqU3OkV9-w",
    warranty: "2 Years Motor Warranty",
    specs: { "Body": "Rust-Free 100% Virgin Plastic Body", "Spin": "Powerful Super Jet Air Dry Spinner", "Power": "Low Power Consumption Motor" },
    featured: false,
    lowest_30_days: false
  },
  {
    id: 404,
    category: "washing-machines",
    brand: "Haier",
    title: "Haier 9.5 Kg Front Load Inverter Washing Machine (HW95-BP14986ES8)",
    model: "HW95-BP14986ES8",
    attr_value: "9.5 Kg",
    price: 178000,
    was_price: 198000,
    emi: 14833,
    rating: 5.0,
    reviews: 23,
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCm9tdMWpfp4TYdLEf86pxgej19uaGeQTcNxarbfwhwiz2onZ1SyFE5Vw4jMwtdObKVft1QpH1YujcrGeNAa-HQ3jml3sFOrpD_46o26NV53s9PuaqaEy6fs_clcG0bF2dlor1KCs3ae1MWJ3DKGhZ3f66oNFV6EleG0upqinZh8m6-wlmDj1vlGgPkbWuZYeNMpknZiB8p0-_7NDkIEoT88Pc5ZTQsetv0MYhQhKSgaQ13RqU3OkV9-w",
    warranty: "10 Years Direct Motion Motor Warranty",
    specs: { "Motor": "Super Silent Direct Motion Inverter Motor", "Hygiene": "99.9% Steam Sterilization & Dual Spray", "RPM": "1400 RPM High Spin" },
    featured: false,
    lowest_30_days: true
  },

  // ================= MICROWAVE OVENS =================
  {
    id: 501,
    category: "microwave-ovens",
    brand: "Dawlance",
    title: "Dawlance 32L Pro Convection Baking Microwave Oven (DW-MD-1085)",
    model: "DW-MD-1085",
    attr_value: "32L",
    price: 63500,
    was_price: 69000,
    emi: 5290,
    rating: 4.8,
    reviews: 65,
    image: "images/microwave-ovens.jpg",
    icon: "microwave",
    warranty: "1 Year Magnetron + 1 Year Parts Warranty",
    specs: { "Cooking Functions": "Baking, Grilling & Solo Microwave", "Menu": "Built-in Pakistani Recipe Menu", "Cavity": "Stainless Steel Rust Free" },
    featured: true,
    lowest_30_days: true
  },
  {
    id: 502,
    category: "microwave-ovens",
    brand: "Dawlance",
    title: "Dawlance 23L Prime Solo Microwave Oven (DW-297)",
    model: "DW-297-GSS",
    attr_value: "23L",
    price: 33000,
    was_price: 36000,
    emi: 2750,
    rating: 4.7,
    reviews: 42,
    image: "images/microwave-ovens.jpg",
    icon: "microwave",
    warranty: "1 Year Magnetron Warranty",
    specs: { "Type": "Solo Fast Heating", "Timer": "Digital 99-Min Timer", "Power Levels": "5 Variable Power Controls" },
    featured: false,
    lowest_30_days: false
  },
  {
    id: 503,
    category: "microwave-ovens",
    brand: "Haier",
    title: "Haier 28L Grill Digital Microwave Oven (HGN-28100EGB)",
    model: "HGN-28100EGB",
    attr_value: "28L",
    price: 52500,
    was_price: 58000,
    emi: 4375,
    rating: 4.8,
    reviews: 38,
    image: "images/microwave-ovens.jpg",
    icon: "microwave",
    warranty: "1 Year Warranty",
    specs: { "Glass": "Full Mirror Black Glass Finish", "Grill": "Quartz High Heat Grill", "Defrost": "Weight & Time Intelligent Defrost" },
    featured: false,
    lowest_30_days: true
  },
  {
    id: 504,
    category: "microwave-ovens",
    brand: "Homage",
    title: "Homage 20L Solo Compact Microwave Oven (HMO-2020S)",
    model: "HMO-2020S",
    attr_value: "20L",
    price: 21500,
    was_price: 24500,
    emi: 1791,
    rating: 4.5,
    reviews: 55,
    image: "images/microwave-ovens.jpg",
    icon: "microwave",
    warranty: "1 Year Magnetron Warranty",
    specs: { "Capacity": "20 Liter Compact", "Control": "Easy Mechanical Knob Dial", "Efficiency": "700W Quick Heating" },
    featured: false,
    lowest_30_days: false
  },

  // ================= AIR COOLERS =================
  {
    id: 601,
    category: "air-coolers",
    brand: "Boss",
    title: "Boss ECM-9000 Pro Desert Air Cooler (55L Tank with Ice Chamber)",
    model: "ECM-9000-Pro",
    attr_value: "55L",
    price: 28500,
    was_price: 32000,
    emi: 2375,
    rating: 4.9,
    reviews: 62,
    image: "images/air-coolers.jpg",
    icon: "air",
    warranty: "1 Year Brand Motor Warranty",
    specs: { "Pads": "3-Side High Density Honeycomb Pads", "Ice Chamber": "Dual Top Ice Compartments", "Throw": "Powerful 45 Ft Air Throw", "Inverter Support": "Runs easily on Solar/UPS" },
    featured: true,
    lowest_30_days: true
  },
  {
    id: 602,
    category: "air-coolers",
    brand: "Super Asia",
    title: "Super Asia Galaxy Series Heavy Air Cooler (70L Tank)",
    model: "Galaxy-Air-70L",
    attr_value: "70L",
    price: 34000,
    was_price: 38500,
    emi: 2833,
    rating: 4.8,
    reviews: 48,
    image: "images/air-coolers.jpg",
    icon: "air",
    warranty: "1 Year Warranty",
    specs: { "Tank": "70 Liter Mega Water Capacity", "Fan": "18\" Aerodynamic Fan Blade", "Body": "Shock-Proof Unbreakable Plastic" },
    featured: false,
    lowest_30_days: false
  },
  {
    id: 603,
    category: "air-coolers",
    brand: "Canon",
    title: "Canon 35L Slim Tower Room Air Cooler with Remote",
    model: "CN-Cool-35",
    attr_value: "35L",
    price: 22500,
    was_price: 25500,
    emi: 1875,
    rating: 4.6,
    reviews: 31,
    image: "images/air-coolers.jpg",
    icon: "air",
    warranty: "1 Year Warranty",
    specs: { "Design": "Space Saving Slim Tower", "Control": "Touch Panel & Wireless Remote", "Speed": "3-Speed Fan with Auto Louvers" },
    featured: false,
    lowest_30_days: true
  },

  // ================= DEEP FREEZERS =================
  {
    id: 701,
    category: "deep-freezers",
    brand: "Waves",
    title: "Waves 14 cu ft Inverter CoolBank Double Door Deep Freezer (WDF-314)",
    model: "WDF-314-CoolBank",
    attr_value: "14 cu ft",
    price: 118000,
    was_price: 132000,
    emi: 9833,
    rating: 4.9,
    reviews: 77,
    image: "images/deep-freezers.jpg",
    icon: "mode_heat",
    warranty: "10 Years Compressor Warranty",
    specs: { "CoolBank Tech": "Retains Cooling up to 100 Hours in Load Shedding", "Compressor": "T3 Inverter Copper Compressor", "Door": "Dual Glass Tops with Soft Grip Handles" },
    featured: true,
    lowest_30_days: true
  },
  {
    id: 702,
    category: "deep-freezers",
    brand: "Dawlance",
    title: "Dawlance 12 cu ft Convertible Inverter Deep Freezer (DF-300)",
    model: "DF-300-Inv",
    attr_value: "12 cu ft",
    price: 106000,
    was_price: 119000,
    emi: 8833,
    rating: 4.8,
    reviews: 39,
    image: "images/deep-freezers.jpg",
    icon: "mode_heat",
    warranty: "12 Years Compressor Warranty",
    specs: { "Function": "Convertible Refrigerator to Freezer Mode", "Lining": "Embossed Stucco Aluminum Anti-Rust Interior" },
    featured: false,
    lowest_30_days: false
  },

  // ================= KITCHEN APPLIANCES (Hobs, Hoods & Cooking Range) =================
  {
    id: 801,
    category: "kitchen-appliances",
    brand: "Nasgas",
    title: "Nasgas 3-Burner Tempered Glass Built-in Kitchen Hob (DG-380)",
    model: "DG-380-Glass",
    attr_value: "3-Burner Hob",
    price: 32000,
    was_price: 36500,
    emi: 2666,
    rating: 4.8,
    reviews: 49,
    image: "images/kitchen-hobs.jpg",
    icon: "skillet",
    warranty: "2 Years Valve & Glass Warranty",
    specs: { "Ignition": "Continuous Battery Auto Pulse Ignition", "Burners": "Heavy Brass Lotus Burners with Cast Iron Pan Trivets", "Glass": "8mm Thermal Shock Proof Glass" },
    featured: true,
    lowest_30_days: true
  },
  {
    id: 802,
    category: "kitchen-appliances",
    brand: "Canon",
    title: "Canon High Suction Auto-Clean Kitchen Chimney Hood (CN-9000)",
    model: "CN-9000-Hood",
    attr_value: "Auto Chimney Hood",
    price: 44000,
    was_price: 49500,
    emi: 3666,
    rating: 4.9,
    reviews: 33,
    image: "images/kitchen-hoods.jpg",
    icon: "heat_pump",
    warranty: "2 Years Brand Warranty",
    specs: { "Suction": "1250 m³/hr High Power Copper Motor", "Sensor": "Wave Motion Gesture Hand Sensor", "Cleaning": "Thermal Auto Clean Oil Collector" },
    featured: false,
    lowest_30_days: true
  },
  {
    id: 803,
    category: "kitchen-appliances",
    brand: "Dawlance",
    title: "Dawlance 5-Burner Heavy Duty Stainless Steel Cooking Range with Oven",
    model: "DCR-500-SS",
    attr_value: "Cooking Range 34\"",
    price: 89000,
    was_price: 99000,
    emi: 7416,
    rating: 4.9,
    reviews: 26,
    image: "images/cooking-range.jpg",
    icon: "countertops",
    warranty: "2 Years Official Warranty",
    specs: { "Burners": "5 High Output Sabaf Burners", "Oven": "Thermostat Controlled Double Glass Oven", "Body": "Heavy Gauge Stainless Steel" },
    featured: true,
    lowest_30_days: true
  },

  // ================= WATER DISPENSERS =================
  {
    id: 901,
    category: "water-dispensers",
    brand: "Dawlance",
    title: "Dawlance 3-Tap Inverter Water Dispenser with Large Refrigerator Cabinet",
    model: "WD-1050-Inv",
    attr_value: "3-Tap Refrigerator",
    price: 46000,
    was_price: 51000,
    emi: 3833,
    rating: 4.8,
    reviews: 51,
    image: "images/water-dispensers.jpg",
    icon: "water_drop",
    warranty: "3 Years Compressor Warranty",
    specs: { "Taps": "3 (Hot, Cold, Ambient Normal)", "Tanks": "100% Food Grade Stainless Steel Tanks", "Cabinet": "20 Liter Bottom Refrigerator Compartment" },
    featured: true,
    lowest_30_days: true
  },
  {
    id: 902,
    category: "water-dispensers",
    brand: "Haier",
    title: "Haier Bottom Load Smart Glass Water Dispenser (HWD-306G)",
    model: "HWD-306G",
    attr_value: "Bottom Load Inverter",
    price: 54000,
    was_price: 59500,
    emi: 4500,
    rating: 4.9,
    reviews: 37,
    image: "images/water-dispensers.jpg",
    icon: "water_drop",
    warranty: "3 Years Compressor Warranty",
    specs: { "Loading": "Easy Hidden Bottom Bottle Loading (No Heavy Lifting)", "Safety": "Child Safety Lock on Hot Water Tap" },
    featured: false,
    lowest_30_days: false
  },

  // ================= SMALL APPLIANCES =================
  {
    id: 1001,
    category: "small-appliances",
    brand: "Philips",
    title: "Philips Essential XXL Digital Air Fryer 7.2L Rapid Air Tech (HD9280)",
    model: "HD9280/90",
    attr_value: "Air Fryer (5L-8L)",
    price: 58500,
    was_price: 66000,
    emi: 4875,
    rating: 4.9,
    reviews: 82,
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCm9tdMWpfp4TYdLEf86pxgej19uaGeQTcNxarbfwhwiz2onZ1SyFE5Vw4jMwtdObKVft1QpH1YujcrGeNAa-HQ3jml3sFOrpD_46o26NV53s9PuaqaEy6fs_clcG0bF2dlor1KCs3ae1MWJ3DKGhZ3f66oNFV6EleG0upqinZh8m6-wlmDj1vlGgPkbWuZYeNMpknZiB8p0-_7NDkIEoT88Pc5ZTQsetv0MYhQhKSgaQ13RqU3OkV9-w",
    icon: "skillet",
    warranty: "2 Years Global Philips Warranty",
    specs: { "Capacity": "7.2 Liter / 1.4kg Fries", "Health": "Up to 90% Less Oil Cooking", "Presets": "7 One-Touch Digital Presets & Keep Warm" },
    featured: true,
    lowest_30_days: true
  },
  {
    id: 1002,
    category: "small-appliances",
    brand: "Westpoint",
    title: "Westpoint 10-in-1 Deluxe Food Factory & Blender Processor (WF-8814)",
    model: "WF-8814",
    attr_value: "Food Factory 10-in-1",
    price: 24500,
    was_price: 28000,
    emi: 2041,
    rating: 4.7,
    reviews: 110,
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCIO0wF_mUwe-jMsGPzegZ4YXPWBZwVOQ_VkgfYfDSaabVTUL3JlQkPiu5UlKxVJ245k-CwF90fYJBe86cfs9h5mIytJyKEjp4s_36lTGSbeJndgf-_rRbZZGNLhGr4ilrM-AuaR4TwGXOC681HrezsC_qF5BpONzdeK_60VBk1Of1b7HSfJWmsHXEMzIZyhk2AppT7L-U_twq2pja_YCJ4Ta9vlBetsMjs_RGmqMjDKRmaYOtGUUOVsw",
    icon: "blender",
    warranty: "2 Years Official Warranty",
    specs: { "Motor": "800W Heavy Duty Pure Copper Motor", "Functions": "Chopper, Juicer, Blender, Dough Kneader, Grinder, Slicer" },
    featured: false,
    lowest_30_days: false
  },
  {
    id: 1003,
    category: "small-appliances",
    brand: "Panasonic",
    title: "Panasonic Heavy Duty 6lb Deluxe Dry Iron (NI-22AWT)",
    model: "NI-22AWT",
    attr_value: "Heavy Dry Iron",
    price: 12500,
    was_price: 14500,
    emi: 1041,
    rating: 5.0,
    reviews: 140,
    image: "images/heavy-irons.jpg",
    icon: "iron",
    warranty: "1 Year Official Warranty",
    specs: { "Weight": "Authentic Heavy 6 lbs Iron", "Soleplate": "Non-Stick Gold Teflon Coating", "Origin": "Made in Malaysia" },
    featured: false,
    lowest_30_days: true
  },
  {
    id: 1004,
    category: "small-appliances",
    brand: "Panasonic",
    title: "Panasonic 21L High Power Cyclone Drum Vacuum Cleaner (MC-YL620)",
    model: "MC-YL620",
    attr_value: "Drum Vacuum 21L",
    price: 36500,
    was_price: 41000,
    emi: 3041,
    rating: 4.9,
    reviews: 64,
    image: "images/vacuum-cleaner.jpg",
    icon: "vacuum",
    warranty: "1 Year Official Warranty",
    specs: { "Suction": "2000W Tough Metal Body Motor", "Capacity": "21 Liter Heavy Dust Tank", "Filter": "Washable Antibacterial Filter" },
    featured: true,
    lowest_30_days: true
  }
];

// Helper functions for currency & stars
function formatPKR(val) {
  return "Rs. " + Number(val).toLocaleString('en-PK');
}

function renderStarIcons(rating) {
  const rounded = Math.round(rating);
  let html = '';
  for (let i = 1; i <= 5; i++) {
    html += `<span class="material-symbols-outlined text-[15px]" style="font-variation-settings: 'FILL' ${i <= rounded ? 1 : 0}">star</span>`;
  }
  return html;
}
